//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class log4net : global::System.Configuration.ApplicationSettingsBase {
        
        private static log4net defaultInstance = ((log4net)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new log4net())));
        
        public static log4net Default {
            get {
                return defaultInstance;
            }
        }
    }
}
